image: node:latest

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm run dev
    - npm run web:deploy
    - ls web/out
    - mv web/out public
  artifacts:
    paths:
      - public
  only:
    - master
